name: Flutter CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'

      - name: Install dependencies
        working-directory: project
        run: flutter pub get

      - name: Run tests
        working-directory: project
        run: flutter test